site_name: PyMoe
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  features:
    - search.suggest
    - search.highlight
    - search.share
    - header.autohide
plugins:
  - search
  - mkdocstrings
  - git-revision-date-localized:
    enable_creation_date: true
    type: datetime
  - git-committers:
    repository: ccubed/PyMoe
    branch: master
repo_url: https://github.com/ccubed/PyMoe
repo_name: ccubed/PyMoe
copyright: Copyright &copy; 2024 Charles Click under the MIT License