[project]
name = "pymoe"
version = "3.0.0"
description = "This is Pymoe. The only python library you'll need if you need information on Anime, Manga, Light Novels, or Visual Novels."
readme = "README.md"
authors = [
    { name = "Charles Click", email = "ccubed.techno@gmail.com" }
]
requires-python = ">=3.10"
license = "MIT"
keywords = ["anime", "manga", "light novel", "visual novel"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Programming Language :: Python :: 3.15",
    "Topic :: Software Development :: Libraries"
]
dependencies = [
    "bs4>=0.0.2",
    "httpx>=0.28.1",
    "orjson>=3.11.5",
]

[project.urls]
Homepage = "https://www.github.com/ccubed/PyMoe"
Documentation = "https://ccubed.github.io/PyMoe/"
Issues = "https://github.com/ccubed/PyMoe/issues"
Repository = "https://github.com/ccubed/PyMoe.git"

[build-system]
requires = ["uv_build>=0.9.18,<0.10.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "black>=25.12.0",
    "isort>=7.0.0",
    "mkdocs>=1.6.1",
    "mkdocs-git-revision-date-localized-plugin>=1.5.0",
    "mkdocs-material>=9.7.0",
    "mkdocstrings>=1.0.0",
    "pytest>=9.0.2",
]
